services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php_slim
    ports:
      - "8100:80"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: php_slim
      DB_USER: root
      DB_PASS: rootpassword

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: php_slim
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - php_slim_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8180:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
volumes:
  php_slim_db_data:
    external: true
